AWSTemplateFormatVersion: 2010-09-09

Description: |
  EC2 instance with security group
  
Resources:
  
  rMySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "AllowSSH"
      GroupDescription: "Allow SSH Access" # Required      
      SecurityGroupIngress: 
      - FromPort: 22
        ToPort: 22
        IpProtocol: tcp # Required
        CidrIp: 0.0.0.0/0
      Tags: 
      - Key: Name
        Value: MySecurityGroup

  rMyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d7a109bf30624c99
      InstanceType: t2.micro
      KeyName: yuli-ec2-keypair
      SecurityGroupIds: 
        - !Ref rMySecGrp
      Tags: 
      - Key: Name
        Value: yuliana-ec2-instance

